# Generated by Django 5.0.2 on 2024-02-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0003_post_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=128)),
                ('title', models.CharField(default='id', max_length=128)),
                ('birt_year', models.CharField(choices=[('ninty_eight', '1998'), ('ninty_nine', '1999'), ('two_thousand', '2000'), ('th_one', '2001')], max_length=12)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
