# Generated by Django 5.0.2 on 2024-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ("ZO'R", "ZO'R"), ("A'LO", "A'LO")], max_length=12, null=True),
        ),
    ]
